/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/github/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 跳转 GitHub 授权 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重定向到 GitHub OAuth 授权页 */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GitHub OAuth 回调 */
        get: {
            parameters: {
                query: {
                    code: string;
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功后重定向到前端，并下发会话 Cookie */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（销毁会话） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当前用户 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户所在工作区列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 工作区列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"][];
                    };
                };
            };
        };
        put?: never;
        /** 新建工作区（创建者成为 owner） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamCreate"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"];
                    };
                };
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作区成员列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成员列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Membership"][];
                    };
                };
            };
        };
        put?: never;
        /** 邀请成员（owner 权限） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team_id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MembershipInvite"];
                };
            };
            responses: {
                /** @description 邀请已发送 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除成员 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team_id: components["parameters"]["TeamId"];
                    user_id: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已移除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 修改成员角色 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    team_id: components["parameters"]["TeamId"];
                    user_id: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleUpdate"];
                };
            };
            responses: {
                /** @description 角色已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/ledgers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户可访问的账本列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账本列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ledger"][];
                    };
                };
            };
        };
        put?: never;
        /** 新建账本（按模板初始化 bean 文件结构） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LedgerCreate"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ledger"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账本详情（含修订号与我的角色） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账本详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ledger"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 删除账本（owner，二次确认参数 confirm=true） */
        delete: {
            parameters: {
                query: {
                    confirm: boolean;
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 从备份 zip 导入并新建账本
         * @description 解压校验（目录结构 + bean-check）后创建新账本；zip 必须包含根目录 index.bean。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        team_id: string;
                        /** @description 新账本名称 */
                        name: string;
                        /** @default CNY */
                        operating_currency?: string;
                        /**
                         * @description 跳过 bean-check 语法校验（用于迁移非标准语法的历史账本）
                         * @default false
                         */
                        skip_validation?: boolean;
                        /**
                         * Format: binary
                         * @description 账本备份 zip
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description 导入并创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupImportResult"];
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导入备份 zip 到已有账本
         * @description 覆盖账本文件（被覆盖文件先快照到 bak/），通过 bean-check 校验后写入并递增修订号。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * @description 跳过 bean-check 语法校验（用于迁移非标准语法的历史账本）
                         * @default false
                         */
                        skip_validation?: boolean;
                        /**
                         * Format: binary
                         * @description 账本备份 zip
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description 导入成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackupImportResult"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账本成员与角色 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成员列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Membership"][];
                    };
                };
            };
        };
        put?: never;
        /** 邀请成员（owner） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MembershipInvite"];
                };
            };
            responses: {
                /** @description 邀请已发送 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前修订号（写操作前检查） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 修订号 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ledger_id: string;
                            /** @example 128 */
                            revision: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 有交易的月份列表（最近在前）
         * @description 供前端月份筛选下拉使用，数据来自账本实际交易（distinct year/month）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 月份列表，如 ["2026-08","2026-07"] */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账户列表（含余额 / 持仓） */
        get: {
            parameters: {
                query?: {
                    status?: "open" | "closed";
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账户列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
            };
        };
        put?: never;
        /** 开户（写入 account/*.bean 的 open 指令） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountOpen"];
                };
            };
            responses: {
                /** @description 开户成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/accounts/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量开户（一次写入多个 open 指令） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountOpenBatch"];
                };
            };
            responses: {
                /** @description 批量开户结果（含跳过项） */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountOpenBatchResult"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/accounts/{account}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账户详情（持仓 / 盈亏 / 余额趋势） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    /** @description 账户全名（URL 编码），如 Assets%3ACash */
                    account: components["parameters"]["AccountParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账户详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountDetail"];
                    };
                };
            };
        };
        /** 重新开户（close 后追加 open 指令恢复使用） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    /** @description 账户全名（URL 编码），如 Assets%3ACash */
                    account: components["parameters"]["AccountParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        opened_on: string;
                    };
                };
            };
            responses: {
                /** @description 已重新开户 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        /** 关闭账户（close 指令） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    /** @description 账户全名（URL 编码），如 Assets%3ACash */
                    account: components["parameters"]["AccountParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        closed_on: string;
                    };
                };
            };
            responses: {
                /** @description 已关闭 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/accounts/{account}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 期初对账（写入 pad + balance 指令） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    /** @description 账户全名（URL 编码），如 Assets%3ACash */
                    account: components["parameters"]["AccountParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date: string;
                        /** @description decimal 字符串 */
                        number: string;
                    };
                };
            };
            responses: {
                /** @description 对账指令已写入 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/account-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账户类型映射（前缀 → 名称） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 类型映射 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountTypeMapping"][];
                    };
                };
            };
        };
        put?: never;
        /** 新增账户类型 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountTypeMapping"];
                };
            };
            responses: {
                /** @description 已新增 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 交易列表
         * @description 按条件筛选交易，默认按日期倒序。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 起始日期 */
                    from?: string;
                    /** @description 结束日期 */
                    to?: string;
                    /** @description 月份，如 2026-08 */
                    month?: string;
                    /** @description 账户精确匹配 */
                    account?: string;
                    /** @description 收款方 / 描述模糊搜索 */
                    q?: string;
                    tag?: string;
                    limit?: number;
                    offset?: number;
                    order?: "asc" | "desc";
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 交易列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Transaction"][];
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 新建交易
         * @description 服务端校验借贷平衡；外币分录自动写入 price 指令并生成 cost。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionCreate"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 交易详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    transaction_id: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 交易详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
            };
        };
        /** 更新交易（整体替换） */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    transaction_id: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionCreate"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        post?: never;
        /** 删除交易 */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    transaction_id: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/transactions/{transaction_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 交易原始 bean 文本 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    transaction_id: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 原始文本 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        /** 用原始文本更新交易 */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    transaction_id: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/plain": string;
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 交易模板列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 模板列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionTemplate"][];
                    };
                };
            };
        };
        put?: never;
        /** 新建模板 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionTemplate"];
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionTemplate"];
                    };
                };
            };
        };
        /** 删除模板 */
        delete: {
            parameters: {
                query: {
                    template_id: string;
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/stats/total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按账户类型汇总 */
        get: {
            parameters: {
                query?: {
                    month?: components["parameters"]["Month"];
                    /** @description 账户前缀过滤，如 Expenses */
                    account?: string;
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 类型 → 金额 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/stats/payee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 收款方统计（金额 / 笔数 / 均值） */
        get: {
            parameters: {
                query?: {
                    month?: components["parameters"]["Month"];
                    /** @description 账户前缀过滤，如 Expenses */
                    account?: string;
                    type?: "total" | "count" | "avg";
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 收款方统计列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsPayee"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/stats/account-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账户余额趋势 */
        get: {
            parameters: {
                query?: {
                    month?: components["parameters"]["Month"];
                    /** @description 账户前缀过滤，如 Assets */
                    account?: string;
                    type?: "day" | "month" | "year" | "sum";
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 趋势点列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsPoint"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/stats/account-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账户资金流向（桑基图数据） */
        get: {
            parameters: {
                query?: {
                    month?: components["parameters"]["Month"];
                    /** @description 账户前缀过滤，如 Expenses */
                    account?: string;
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 节点与边 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nodes: {
                                name?: string;
                            }[];
                            links: {
                                source?: number;
                                target?: number;
                                value?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 事件列表（按日期倒序） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 事件列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"][];
                    };
                };
            };
        };
        put?: never;
        /** 添加事件（event 指令） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            responses: {
                /** @description 已添加 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** 删除事件 */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/source-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 源文件目录树 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 相对路径列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/source-files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取源文件内容 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    /** @description 相对路径（URL 编码），如 month/2026-08.bean */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 文件内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                422: components["responses"]["Unprocessable"];
            };
        };
        /** 更新源文件（保存前备份 + bean-check 校验） */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/plain": string;
                };
            };
            responses: {
                /** @description 已保存 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["Unprocessable"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/imports/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传账单 CSV 并预览（不落账） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    source: "alipay" | "wechat" | "icbc" | "abc";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description 预览结果（含 AI 分类建议） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRow"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/imports/{source}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认导入（写入账本） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                    source: "alipay" | "wechat" | "icbc" | "abc";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rows: components["schemas"]["ImportRow"][];
                    };
                };
            };
            responses: {
                /** @description 导入结果（成功 / 失败列表） */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created?: number;
                            failed?: {
                                index?: number;
                                reason?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 币种与最新汇率 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 币种列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Currency"][];
                    };
                };
            };
        };
        put?: never;
        /** 新增币种 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example USD */
                        currency: string;
                        /** @example 美元 */
                        name: string;
                        /** @example $ */
                        symbol?: string;
                    };
                };
            };
            responses: {
                /** @description 已新增 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/currencies/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 同步最新汇率（写入 price 指令） */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
                    "If-Revision-Match": components["parameters"]["IfRevisionMatch"];
                };
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 同步后的币种列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Currency"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/ai/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自然语言记账（生成待确认交易草稿）
         * @description AI 不直接写账；返回草稿与建议，由调用方确认后调用交易创建接口。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 昨天星巴克咖啡 38 元 */
                        text: string;
                    };
                };
            };
            responses: {
                /** @description 待确认交易草稿 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiRecordResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/ai/record/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自然语言批量记账（一次生成多条待确认交易草稿）
         * @description AI 不直接写账；一次可描述多笔交易，返回草稿数组，由调用方确认后逐笔调用创建接口。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @example 昨天星巴克 38 元
                         *     前天打车 120 元
                         */
                        text: string;
                    };
                };
            };
            responses: {
                /** @description 待确认交易草稿数组 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiRecordBatchResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/ai/record/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 对话式批量记账（多轮生成 / 调整草稿）
         * @description 传入对话历史与当前草稿，AI 返回调整后的完整草稿数组；前端勾选后逐笔创建。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiRecordChatRequest"];
                };
            };
            responses: {
                /** @description 待确认交易草稿数组 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiRecordBatchResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/ai/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成账本总结 */
        post: {
            parameters: {
                query?: {
                    month?: components["parameters"]["Month"];
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 文字总结 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/ai/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 洞察与异常检测（重复扣款 / 大额支出 / 环比异常） */
        get: {
            parameters: {
                query?: {
                    month?: components["parameters"]["Month"];
                };
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 洞察列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            insights: {
                                /** @enum {string} */
                                type: "duplicate" | "large_expense" | "trend_change";
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledgers/{ledger_id}/ai/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 批量设计账户（生成待确认账户列表）
         * @description AI 不直接写账；返回建议账户列表，由调用方确认后调用批量开户接口。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ledger_id: components["parameters"]["LedgerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 我需要这些账户：招商银行储蓄卡、日常餐饮、工资收入 */
                        text: string;
                    };
                };
            };
            responses: {
                /** @description 建议账户列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiAccountsResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API Key 列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key 列表（不含明文） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKey"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建 API Key（明文仅返回一次） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @enum {string} */
                        scope: "read-only" | "read-write" | "ai";
                    };
                };
            };
            responses: {
                /** @description 创建成功，secret 字段仅此一次可见 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKey"] & {
                            /** @example bgsk_xxxxxxxx */
                            secret: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 吊销 API Key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已吊销 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志（owner） */
        get: {
            parameters: {
                query?: {
                    ledger_id?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 审计记录 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLog"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MCP Server（SSE 传输）
         * @description 供 Claude / Cursor 等 Agent 连接；工具列表见 integration 文档，认证用 Bearer API Key。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE 事件流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** MCP Server（Streamable HTTP） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description MCP JSON-RPC 响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description 业务错误码：VALIDATION / UNAUTHORIZED / FORBIDDEN / NOT_FOUND / LEDGER_STALE / UNBALANCED / INTERNAL
             * @example LEDGER_STALE
             */
            code: string;
            message: string;
            /** @description 附加信息，如 409 时的 current_revision */
            details?: Record<string, never>;
            request_id?: string;
        };
        User: {
            id: string;
            github_login: string;
            display_name: string;
            email?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Team: {
            id: string;
            name: string;
            role: components["schemas"]["Role"];
            member_count?: number;
            ledger_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        TeamCreate: {
            /** @example 家庭 */
            name: string;
        };
        Membership: {
            user_id: string;
            github_login: string;
            display_name?: string;
            role: components["schemas"]["Role"];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "pending";
        };
        MembershipInvite: {
            github_login_or_email: string;
            role: components["schemas"]["Role"];
        };
        RoleUpdate: {
            role: components["schemas"]["Role"];
        };
        /** @enum {string} */
        Role: "owner" | "editor" | "viewer";
        Ledger: {
            id: string;
            team_id?: string;
            name: string;
            data_path?: string;
            /** @example CNY */
            operating_currency: string;
            /** Format: date */
            start_date?: string;
            /** @default Equity:OpeningBalances */
            opening_balances: string;
            /** @default true */
            is_bak: boolean;
            revision: number;
            role: components["schemas"]["Role"];
            member_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        LedgerCreate: {
            team_id: string;
            name: string;
            /** @default CNY */
            operating_currency: string;
            /** Format: date */
            start_date?: string;
            /** @default Equity:OpeningBalances */
            opening_balances: string;
            /** @default true */
            is_bak: boolean;
        };
        BackupImportResult: {
            ledger?: components["schemas"]["Ledger"];
            /** @description 导入后修订号（导入已有账本时返回） */
            revision?: number;
            /** @description 写入的文件相对路径列表 */
            files: string[];
            warnings?: string[];
        };
        Account: {
            /** @example Assets:Cash */
            account: string;
            /** @enum {string} */
            type: "Assets" | "Liabilities" | "Income" | "Expenses" | "Equity";
            /** @enum {string} */
            status: "open" | "closed";
            /** Format: date */
            opened_on?: string;
            /** Format: date */
            closed_on?: string | null;
            currency?: string;
            commodities?: components["schemas"]["Currency"][];
            positions?: {
                number?: string;
                currency?: string;
                currency_symbol?: string;
            }[];
            market_number?: string;
            market_currency?: string;
        };
        AccountOpen: {
            /** @example Assets:Bank:招商银行 */
            account: string;
            /** Format: date */
            opened_on: string;
            /** @description 多币种用逗号分隔 */
            currency?: string;
            /**
             * @default none
             * @enum {string}
             */
            booking: "fifo" | "average" | "none";
        };
        AccountOpenBatch: {
            accounts: components["schemas"]["AccountOpen"][];
        };
        AccountOpenBatchResult: {
            created: components["schemas"]["Account"][];
            skipped?: {
                account: string;
                reason: string;
            }[];
        };
        AiAccountsResult: {
            accounts: {
                /** @example Assets:Bank:招商银行 */
                account: string;
                /** @description 多币种用逗号分隔 */
                currency?: string;
            }[];
            notes?: string;
        };
        AccountDetail: components["schemas"]["Account"] & {
            market_number?: string;
            market_currency?: string;
            cost?: string;
            pnl?: string;
            balance_trend?: components["schemas"]["StatsPoint"][];
        };
        AccountTypeMapping: {
            /** @example Assets */
            prefix: string;
            /** @example 资产 */
            name: string;
        };
        Transaction: {
            id: string;
            /** Format: date */
            date: string;
            /**
             * @default *
             * @enum {string}
             */
            flag: "*" | "!";
            payee?: string;
            narration?: string;
            tags?: string[];
            links?: string[];
            postings: components["schemas"]["Posting"][];
        };
        TransactionCreate: {
            /** Format: date */
            date: string;
            /**
             * @default *
             * @enum {string}
             */
            flag: "*" | "!";
            payee?: string;
            narration?: string;
            tags?: string[];
            links?: string[];
            postings: components["schemas"]["Posting"][];
            /** @description 分期记账日期列表，金额自动均分 */
            divide_dates?: string[];
        };
        Posting: {
            /** @example Expenses:Food */
            account: string;
            units?: components["schemas"]["Amount"];
            cost?: components["schemas"]["Cost"];
            price?: components["schemas"]["Amount"];
        };
        Amount: {
            /**
             * @description decimal 字符串，避免浮点误差
             * @example -120.00
             */
            number: string;
            /** @example CNY */
            currency: string;
        };
        Cost: {
            number?: string;
            currency?: string;
            /** Format: date */
            date?: string;
            label?: string;
        };
        TransactionTemplate: {
            id?: string;
            name: string;
            payee?: string;
            narration: string;
            tags?: string[];
            postings: components["schemas"]["Posting"][];
        };
        Event: {
            /** Format: date */
            date: string;
            /** @example 工作 */
            type: string;
            description: string;
        };
        ImportRow: {
            index?: number;
            /** Format: date */
            date: string;
            payee?: string;
            narration: string;
            number: string;
            /** @default CNY */
            currency: string;
            /** @description AI / 规则建议账户 */
            suggested_account?: string;
            /** @description 0-1 */
            confidence?: number;
            /** @enum {string} */
            status?: "matched" | "suggested" | "unclassified";
        };
        Currency: {
            currency: string;
            name: string;
            symbol?: string;
            is_operating?: boolean;
            price?: string;
            /** Format: date */
            price_date?: string;
        };
        StatsPayee: {
            payee?: string;
            count?: number;
            amount?: string;
        };
        StatsPoint: {
            date?: string;
            amount?: string;
            operating_currency?: string;
        };
        AiRecordChatRequest: {
            messages: {
                /** @enum {string} */
                role: "user" | "assistant";
                content: string;
            }[];
            drafts?: components["schemas"]["Transaction"][];
        };
        AiRecordBatchResult: {
            drafts: components["schemas"]["Transaction"][];
            notes?: string;
        };
        AiRecordResult: {
            draft: components["schemas"]["TransactionCreate"] & {
                account_suggestions?: {
                    posting_index?: number;
                    account?: string;
                    confidence?: number;
                }[];
            };
            notes?: string;
        };
        ApiKey: {
            id: string;
            name: string;
            /** @enum {string} */
            scope: "read-only" | "read-write" | "ai";
            prefix?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string | null;
            revoked?: boolean;
        };
        AuditLog: {
            id: number;
            ledger_id?: string | null;
            user_id?: string;
            /** @description GitHub 登录名或 API Key 名称 */
            actor?: string;
            action: string;
            object?: string;
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description 请求参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未登录或会话失效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 角色权限不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 修订号过期或资源冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 语义校验失败（借贷不平衡 / bean-check 失败 / 路径越界） */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务器错误 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        LedgerId: string;
        TeamId: string;
        UserId: string;
        /** @description 账户全名（URL 编码），如 Assets%3ACash */
        AccountParam: string;
        TransactionId: string;
        Month: string;
        /** @description 当前账本修订号；不匹配时返回 409 LEDGER_STALE */
        IfRevisionMatch: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
